version: '3'
services:
  api:
    container_name: 'nestjs_ddd'
    build: .
    ports:
      - '${HTTP_PORT}:${HTTP_PORT}'
      - '${HTTPS_PORT}:${HTTPS_PORT}'
    environment:
      - NODE_ENV='${NODE_ENV}'
      - SSL_KEY_PATH='${SSL_KEY_PATH}'
      - SSL_CERT_PATH=${SSL_CERT_PATH}
    volumes:
      - ./ssl:/app/ssl:ro
    # Puedes agregar más variables de entorno según las necesidades de tu aplicación
